version: "3.8"

services:
  db:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27018:27017"
    restart: always
    networks:
      - demoexpress_network
    volumes:
      - mongodb:/data/db

  myapp:
    build: .
    container_name: demoexpress
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}  # 👈 THÊM DÒNG NÀY nếu chưa có
    depends_on:
      - db
    restart: always
    networks:
      - demoexpress_network


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - myapp
    networks:
      - demoexpress_network

networks:
  demoexpress_network:
    driver: bridge

volumes:
  mongodb:
    driver: local
